framework: mocha
tier: large
postMerge:
  pattern:
    - './test/all/node/test-exports.js'
    - './test/all/node/test-jsdocs.js'
    - './test/all/node/test-package.js'
    - './test/all/node/test-prod-builds.js'
    - './test/all/node/test-yarn-installation.js'
preMerge:
  pattern:
    - './test/all/node/test-exports.js'
    - './test/all/node/test-jsdocs.js'
    - './test/all/node/test-package.js'
preRun:
  command:
    - npm install
postRun:
  command:
    - node --version
version: 2.0
