framework: mocha
tier: xlarge
postMerge:
  pattern:
    - './test/**/node/*.js'
preMerge:
  pattern:
    - './test/**/node/*.js'
preRun:
  command:
    - npm install
postRun:
  command:
    - node --version
version: 2.0
