framework: mocha
tier: large
postMerge:
  pattern:
    - './test/all/node/*.js'
preMerge:
  pattern:
    - './test/all/node/*.js'
preRun:
  command:
    - npm install
postRun:
  command:
    - node --version
version: 2.0
